services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retro-type-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:cn6jc0qxvjfsmsq8@retrotype-db-sz18fa:5432/retroType
      - SESSION_SECRET=retro_type_secret_key_12345
      - NODE_ENV=production

